export default [
  {
    name: "Smart Classic Cloudy Grey Wide Groove",
    img: "https://i.ibb.co/MMs6XMb/Smart-Classic-Cloudy-Grey.png    ",
    desc: "wide lines    ",
    cat: "smart_classic",
    price: "",
    st_name: "ad8    ",
    size: { l: "3800", t: "22", w: "152", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartclassic_wide.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Classic Wide Groove Cloudy Grey",
      Dutch: "Smart Classic brede groef Cloudy Grey",
      Danish: "Smart Classic bred rillet Cloudy Grey",
      Swedish: "Smart Classic Breda Skåror Cloudy Grey",
      German: "Smart Classic breite Rille, Cloudy Grey",
    },
  },
  {
    name: "Smart Classic Ipe Wide Groove",
    img: "https://i.ibb.co/TqsvDgg/Smart-Classic-Ipe.png    ",
    desc: "wide lines    ",
    cat: "smart_classic",
    price: "",
    st_name: "ad9    ",
    size: { l: "3800", t: "22", w: "152", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartclassic_wide.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Classic Wide Groove Ipe",
      Dutch: "Smart Classic brede groef Ipe",
      Danish: "Smart Classic bred rillet Ipe",
      Swedish: "Smart Classic Breda Skåror Ipé",
      German: "Smart Classic breite Rille, Ipe",
    },
  },
  {
    name: "Smart Classic Beach Grey Wide Groove",
    img: "https://i.ibb.co/vJNnPZN/Classic-Side-1-Beach-Grey.png",
    desc: "Wide lines    ",
    cat: "smart_classic",
    price: "",
    st_name: "za1",
    size: { l: "3800", t: "22", w: "152", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartclassic_wide.png",
    fixigkit: "za3",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    },
  },
  {
    name: "Smart Classic Chocolate Wide Groove",
    img: "https://i.ibb.co/Bswky20/Classic-Side-1-Chocolate.png",
    desc: "Wide lines      ",
    cat: "smart_classic",
    price: "",
    st_name: "za2    ",
    size: { l: "3800", t: "22", w: "152", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartclassic_wide.png",
    fixigkit: "1",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    },
  },
  {
    name: "Smart Classic Teak Wide Groove",
    img: "https://i.ibb.co/6WN8psS/Classic-Side-1-Teak.png    ",
    desc: "Wide lines      ",
    cat: "smart_classic",
    price: "",
    st_name: "za3    ",
    size: { l: "3800", t: "22", w: "152", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartclassic_wide.png",
    fixigkit: "1",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    },
  },
  {
    name: "Smart Classic Walnut Wide Groove",
    img: "https://i.ibb.co/fF6Mht8/Smart-Classic-Walnut.png    ",
    desc: "wide lines    ",
    cat: "smart_classic",
    price: "",
    st_name: "ae1",
    size: { l: "3800", t: "22", w: "152", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartclassic_wide.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Classic Wide Groove Walnut",
      Dutch: "Smart Classic brede groef Walnut",
      Danish: "Smart Classic bred rillet Walnut",
      Swedish: "Smart Classic Breda Skåror Walnut",
      German: "Smart Classic breite Rille, Walnut",
    },
  },
  {
    name: "Smart Regular Beach Grey Narrow Ribbed",
    img: "https://i.ibb.co/XyxRpTt/Smart-Regular-Beach-Grey.png    ",
    desc: "Narrow lines    ",
    cat: "smart_regular",
    price: "",
    st_name: "ae7    ",
    size: { l: "3800", t: "22", w: "142", ac: "6.9" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartregular_narrow.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Regular Narrow Ribbed Beach Grey",
      Dutch: "Smart Regular fijn geribbeld Beach Grey",
      Danish: "Smart Regular ribbet Beach Grey",
      Swedish: "Smart Regular Smal Räfflad Beach Grey",
      German: "Smart regulär schmal gerippt, Beach Grey",
    },
  },
  {
    name: "Smart Regular Charcoal Narrow Ribbed",
    img: "https://i.ibb.co/jh37nKf/Smart-Regular-Charcoal.png    ",
    desc: "Narrow lines    ",
    cat: "smart_regular",
    price: "    ",
    st_name: "ae8",
    size: { l: "3800", t: "22", w: "142", ac: "6.9" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartregular_narrow.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Regular Narrow Ribbed Charcoal",
      Dutch: "Smart Regular fijn geribbeld Charcoal",
      Danish: "Smart Regular ribbet Charcoal",
      Swedish: "Smart Regular Smal Räfflad Charcoal",
      German: "Smart regulär schmal gerippt, Charcoal",
    },
  },
  {
    name: "Smart Regular Chocolate Narrow Ribbed",
    img: "https://i.ibb.co/qxN1Gds/Smart-Regular-Chocolate.png    ",
    desc: "Narrow lines    ",
    cat: "smart_regular",
    price: "",
    st_name: "ae9    ",
    size: { l: "3800", t: "22", w: "142", ac: "6.9" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartregular_narrow.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Regular Narrow Ribbed Chocolate",
      Dutch: "Smart Regular fijn geribbeld Chocolate",
      Danish: "Smart Regular ribbet Chocolate",
      Swedish: "Smart Regular Smal Räfflad Chocolate",
      German: "Smart regulär schmal gerippt, Chocolate",
    },
  },
  {
    name: "Smart Regular Coffee Brown Narrow Ribbed",
    img: "https://i.ibb.co/hYwL7XV/Smart-Regular-Coffee-Brown.png    ",
    desc: "Narrow lines    ",
    cat: "smart_regular",
    price: "",
    st_name: "af1",
    size: { l: "3800", t: "22", w: "142", ac: "6.9" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartregular_narrow.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Regular Narrow Ribbed Coffee Brown",
      Dutch: "Smart Regular fijn geribbeld Coffee Brown",
      Danish: "Smart Regular ribbet Coffee Brown",
      Swedish: "Smart Regular Smal Räfflad Coffee Brown",
      German: "Smart regulär schmal gerippt, Coffee Brown",
    },
  },
  {
    name: "Smart Regular Teak Narrow Ribbed",
    img: "https://i.ibb.co/SQrZQqy/Smart-Regular-Teak.png    ",
    desc: "Narrow lines    ",
    cat: "smart_regular",
    price: "",
    st_name: "af2",
    size: { l: "3800", t: "22", w: "142", ac: "6.9" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartregular_narrow.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Regular Narrow Ribbed Teak",
      Dutch: "Smart Regular fijn geribbeld Teak",
      Danish: "Smart Regular ribbet Teak",
      Swedish: "Smart Regular Smal Räfflad Teak",
      German: "Smart regulär schmal gerippt, Teak",
    },
  },
  {
    name: "Smart Marine Beach Grey Smooth",
    img: "https://i.ibb.co/sskk0bS/Smart-Natural-Beach-Grey.png    ",
    desc: "",
    cat: "smart_marine",
    price: "",
    st_name: "ae2",
    size: { l: "3800", t: "22", w: "142", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartcap_woodtexture.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Marine Smooth Beach Grey",
      Dutch: "Smart Marine glad geschaafd Beach Grey",
      Danish: "Smart Marine glat Beach Grey",
      Swedish: "Smart Marine Slät Beach Grey",
      German: "Smart Marine glatt, Beach Grey",
    },
  },
  {
    name: "Smart Marine Charcoal Smooth",
    img: "https://i.ibb.co/jzjthFv/Smart-Natural-Charcoal.png    ",
    desc: "",
    cat: "smart_marine",
    price: "",
    st_name: "ae3    ",
    size: { l: "3800", t: "22", w: "142", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartcap_woodtexture.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Marine Smooth Charcoal",
      Dutch: "Smart Marine glad geschaafd Charcoal",
      Danish: "Smart Marine glat Charcoal",
      Swedish: "Smart Marine Slät Charcoal",
      German: "Smart Marine glatt, Charcoal",
    },
  },
  {
    name: "Smart Marine Chocolate Smooth",
    img: "https://i.ibb.co/jzk2SY2/Smart-Natural-Chocolate.png    ",
    desc: "",
    cat: "smart_marine",
    price: "",
    st_name: "ae4    ",
    size: { l: "3800", t: "22", w: "142", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartcap_woodtexture.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Marine Smooth Chocolate",
      Dutch: "Smart Marine glad geschaafd Chocolate",
      Danish: "Smart Marine glat Chocolate",
      Swedish: "Smart Marine Slät Chocolate",
      German: "Smart Marine glatt, Chocolate",
    },
  },
  {
    name: "Smart Marine Coffee Brown Smooth",
    img: "https://i.ibb.co/LxB57VL/Smart-Natural-Coffee-Brown.png    ",
    desc: "",
    cat: "smart_marine",
    price: "",
    st_name: "ae5    ",
    size: { l: "3800", t: "22", w: "142", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartcap_woodtexture.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Marine Smooth Coffee Brown",
      Dutch: "Smart Marine glad geschaafd Coffee Brown",
      Danish: "Smart Marine glat Coffee Brown",
      Swedish: "Smart Marine Slät Coffee Brown",
      German: "Smart Marine glatt, Coffee Brown",
    },
  },
  {
    name: "Smart Marine Teak Smooth",
    img: "https://i.ibb.co/MMHZLDW/Smart-Natural-Teak.png    ",
    desc: "",
    cat: "smart_marine",
    price: "",
    st_name: "ae6    ",
    size: { l: "3800", t: "22", w: "142", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartcap_woodtexture.png",
    fixigkit: "1",
    multi_language: {
      English: "Smart Marine Smooth Teak",
      Dutch: "Smart Marine glad geschaafd Teak",
      Danish: "Smart Marine glat Teak",
      Swedish: "Smart Marine Slät Teak",
      German: "Smart Marine glatt, Teak",
    },
  },
  {
    name: "Ultra Smart Baltic Grey Wood-Texture Deep Embossed",
    img: "https://i.ibb.co/tL04m00/Smart-Cap-Baltic-Grey.png    ",
    desc: "wood-texture    ",
    cat: "smart_cap",
    price: "",
    st_name: "af3",
    size: { l: "3600", t: "22", w: "142", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartcap_woodtexture.png",
    fixigkit: "1",
    multi_language: {
      English: "Ultra Smart Wood-Texture Deep Embossed Baltic Grey",
      Dutch: "Ultra Smart getextureerde en veerkrachtige toplaag Baltic Grey",
      Danish: "Ultra Smart træ tekstur Baltic Grey",
      Swedish: "Ultra Smart Inkapslad Präglad Trä-Textur Baltic Grey",
      German: "Ultra Smart Holzstruktur tief geprägt, Baltic Grey",
    },
  },
  {
    name: "Ultra Smart Baltic Brown Wood-Texture Deep Embossed",
    img: "https://i.ibb.co/cT2KDP4/Smart-Cap-Baltic-Brown.png    ",
    desc: "wood-texture",
    cat: "smart_cap",
    price: "",
    st_name: "af4",
    size: { l: "3600", t: "22", w: "142", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "smartcap_woodtexture.png",
    fixigkit: "1",
    multi_language: {
      English: "Ultra Smart Wood-Texture Deep Embossed Baltic Brown",
      Dutch: "Ultra Smart getextureerde en veerkrachtige toplaag Baltic Brown",
      Danish: "Ultra Smart træ tekstur Baltic Brown",
      Swedish: "Ultra Smart Inkapslad Präglad Trä-Textur Baltic Brown",
      German: "Ultra Smart Holzstruktur tief geprägt, Baltic Brown",
    },
  },
  
  {
    name: "Marine 40 Beach Grey ribbed surface Narrow lines",
    img: "https://i.ibb.co/vYJvPtK/af5.jpg",
    desc: "",
    cat: "marine_40",
    price: "",
    st_name: "af5",
    size: { l: "4800", t: "19", w: "146", ac: "6.7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marine40_narrow.png",
    fixigkit: "6",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 40 Charcoal ribbed surface Narrow lines",
    img: "https://i.ibb.co/wL7RtCM/af6.jpg",
    desc: "",
    cat: "marine_40",
    price: "",
    st_name: "af6",
    size: { l: "4800", t: "19", w: "146", ac: "6.7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marine40_narrow.png",
    fixigkit: "6",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 40 Chocolate ribbed surface Narrow lines",
    img: "https://i.ibb.co/kHkxwrt/af7.jpg",
    desc: "",
    cat: "marine_40",
    price: "",
    st_name: "af7",
    size: { l: "4800", t: "19", w: "146", ac: "6.7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marine40_narrow.png",
    fixigkit: "6",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 40 Teak ribbed surface Narrow lines",
    img: "https://i.ibb.co/W0FHCFs/af8.jpg",
    desc: "",
    cat: "marine_40",
    price: "",
    st_name: "af8",
    size: { l: "4800", t: "19", w: "146", ac: "6.7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marine40_narrow.png",
    fixigkit: "6",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 40 Beach Grey grooved surface Wide lines",
    img: "https://i.ibb.co/0GxSBQY/ag1.jpg",
    desc: "",
    cat: "marine_40",
    price: "",
    st_name: "ag1",
    size: { l: "4800", t: "19", w: "146", ac: "6.7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marine40_wide.png",
    fixigkit: "6",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 40 Charcoal grooved surface Wide lines",
    img: "https://i.ibb.co/nBG4mFV/ag2.jpg",
    desc: "",
    cat: "marine_40",
    price: "",
    st_name: "ag2",
    size: { l: "4800", t: "19", w: "146", ac: "6.7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marine40_wide.png",
    fixigkit: "6",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 40 Chocolate grooved surface Wide lines",
    img: "https://i.ibb.co/7RXrnZk/ag3.jpg",
    desc: "",
    cat: "marine_40",
    price: "",
    st_name: "ag3",
    size: { l: "4800", t: "19", w: "146", ac: "6.7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marine40_wide.png",
    fixigkit: "6",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 40 Teak grooved surface Wide lines",
    img: "https://i.ibb.co/R6c67Bh/ag4.jpg",
    desc: "",
    cat: "marine_40",
    price: "",
    st_name: "ag4",
    size: { l: "4800", t: "19", w: "146", ac: "6.7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marine40_wide.png",
    fixigkit: "6",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 40 Brazilian Oak grooved surface wide lines    ",
    img: "https://i.ibb.co/PM0dWcf/af9.jpg",
    desc: "",
    cat: "marine_40",
    price: "",
    st_name: "ah9",
    size: { l: "4800", t: "19", w: "146", ac: "6.7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marine40_wide.png",
    fixigkit: "6",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    },
  },
  {
    name: "Marine 60 Beach Grey ribbed surface Narrow lines",
    img: "https://i.ibb.co/pXVmTVJ/Marine-60-Narrow-Lines-beach-grey.png",
    desc: "",
    cat: "marine_60",
    price: "",
    st_name: "ag6",
    size: { l: "4800", t: "22", w: "150", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marine60_narrow.png",
    fixigkit: "8",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 60 Stone Grey ribbed surface Narrow lines",
    img: "https://i.ibb.co/VvWqHbV/Marine-60-Narrow-Lines-stone-grey.png",
    desc: "",
    cat: "marine_60",
    price: "",
    st_name: "ag9",
    size: { l: "4800", t: "22", w: "150", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marine60_narrow.png",
    fixigkit: "8",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 60 American Walnut ribbed surface Narrow lines",
    img:
      "https://i.ibb.co/pK8rGBS/https://i.ibb.co/r7229VX/Marine-60-Narrow-Lines-Walnut.png",
    desc: "",
    cat: "marine_60",
    price: "",
    st_name: "ah1",
    size: { l: "4800", t: "22", w: "150", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marine60_narrow.png",
    fixigkit: "8",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 60 Ipé ribbed surface Narrow lines",
    img: "https://i.ibb.co/Sf4RG8M/Marine-60-Narrow-Lines-Ip.png",
    desc: "",
    cat: "marine_60",
    price: "",
    st_name: "ah2",
    size: { l: "4800", t: "22", w: "150", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marine60_narrow.png",
    fixigkit: "8",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 60 Beach Grey smooth surface",
    img: "https://i.ibb.co/Sdm7dFH/Marine-60-plan-surface-beach-grey.png",
    desc: "",
    cat: "marine_60",
    price: "",
    st_name: "ah3",
    size: { l: "4800", t: "22", w: "150", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marine60.png",
    fixigkit: "8",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 60 Stone Grey smooth surface striking texture",
    img: "https://i.ibb.co/bFfk16m/Marine-60-Smooth-stone-Grey.png",
    desc: "",
    cat: "marine_60",
    price: "",
    st_name: "ah6",
    size: { l: "4800", t: "22", w: "150", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marine60.png",
    fixigkit: "8",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 60 American Walnut smooth surface striking texture",
    img: "https://i.ibb.co/X5F97BH/Marine-60-Smooth-Surface-Walnut.png",
    desc: "",
    cat: "marine_60",
    price: "",
    st_name: "ah7",
    size: { l: "4800", t: "22", w: "150", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marine60.png",
    fixigkit: "8",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine 60 Ipé smooth surface striking texture",
    img: "https://i.ibb.co/YD0G65C/Marine-60-Smooth-Surface-Ip.png",
    desc: "",
    cat: "marine_60",
    price: "",
    st_name: "ah8",
    size: { l: "4800", t: "22", w: "150", ac: "6.5" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marine60.png",
    fixigkit: "8",
    multi_language: {
      English: "",
      Dutch: "",
      Danish: "",
      Swedish: "",
      German: "",
    }
  },
  {
    name: "Marine Art Rustic Brown Wood-Texture deep Embossed",
    img: "https://i.ibb.co/PxRNtMp/Marine-Art-Side-1-Rustic-Brown.png    ",
    desc: "wood-texture    ",
    cat: "marine_art",
    price: "",
    st_name: "ac3    ",
    size: { l: "3800", t: "18", w: "130", ac: "7.52" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marineart_woodtexture.png",
    fixigkit: "6",
    multi_language: {
      English: "Marine Art Wood-Texture deep Embossed Rustic Brown",
      Dutch: "Marine Art details van echt hout Rustic Brown",
      Danish: "Marine Art træ tekstur Rustic Brown",
      Swedish: "Marine Art Präglad Trä Textur Rustic Brown",
      German: "Marine Art Holzstruktur tief geprägt, Rustic Brown",
    },
  },
  {
    name: "Marine Art Rustic Grey Wood-Texture deep Embossed",
    img: "https://i.ibb.co/w64HNb7/Marine-Art-Side-1-Rustic-Grey.png    ",
    desc: "wood-texture    ",
    cat: "marine_art",
    price: "",
    st_name: "ac4    ",
    size: { l: "3800", t: "18", w: "130", ac: "7.52" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marineart_woodtexture.png",
    fixigkit: "6",
    multi_language: {
      English: "Marine Art Wood-Texture deep Embossed Rustic Grey",
      Dutch: "Marine Art details van echt hout Rustic Grey",
      Danish: "Marine Art træ tekstur Rustic Grey",
      Swedish: "Marine Art Präglad Trä Textur Rustic Grey",
      German: "Marine Art Holzstruktur tief geprägt, Rustic Grey",
    },
  },
  {
    name: "Marine Art Rustic Brown Smooth",
    img: "https://i.ibb.co/3kpN09W/Marine-Art-Side-2-Rustic-Brown.png    ",
    desc: "",
    cat: "marine_art",
    price: "",
    st_name: "ac5    ",
    size: { l: "3800", t: "18", w: "130", ac: "7.52" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marineart_woodtexture.png",
    fixigkit: "6",
    multi_language: {
      English: "Marine Art Smooth Rustic Brown",
      Dutch: "Marine Art glad geschaafd Rustic Brown",
      Danish: "Marine Art glat Rustic Brown",
      Swedish: "Marine Art Präglad Trä Textur Rustic Brown",
      German: "Marine Art glatt, Rustic Brown",
    },
  },
  {
    name: "Marine Art Rustic Grey Smooth",
    img: "https://i.ibb.co/X5kzK2N/Marine-Art-Side-2-Rustic-Grey.png    ",
    desc: "",
    cat: "marine_art",
    price: "",
    st_name: "ac6    ",
    size: { l: "3800", t: "18", w: "130", ac: "7.52" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marineart_woodtexture.png",
    fixigkit: "6",
    multi_language: {
      English: "Marine Art Smooth Rustic Grey",
      Dutch: "Marine Art glad geschaafd Rustic Grey",
      Danish: "Marine Art glat Rustic Grey",
      Swedish: "Marine Art Präglad Trä Textur Rustic Grey",
      German: "Marine Art glatt, Rustic Grey",
    },
  },
  {
    name: "MarineCap Baltic Grey Wood-Texture Deep Embossed",
    img: "https://i.ibb.co/kBcWJj3/Marine-Cap-Side-1-Baltic-Grey.png    ",
    desc: "wood-texture    ",
    cat: "marine_cap",
    price: "",
    st_name: "ac7    ",
    size: { l: "4800", t: "19.5", w: "140", ac: "7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marineart_woodtexture.png",
    fixigkit: "6",
    multi_language: {
      English: "MarineCap Wood-Texture Deep Embossed Baltic Grey",
      Dutch: "MarineCap getextureerde en veerkrachtige toplaag Baltic Grey",
      Danish: "MarineCap træ tekstur Baltic Grey",
      Swedish: "MarineCap Inkapslad Präglad Trä-Textur Baltic Grey",
      German: "Marine Cap Holzstruktur tief geprägt, Baltic Grey",
    },
  },
  {
    name: "MarineCap Baltic Brown Wood-Texture Deep Embossed",
    img: "https://i.ibb.co/7131LYW/Marine-Cap-Side-1-Baltic-Brown.png    ",
    desc: "wood-texture    ",
    cat: "marine_cap",
    price: "",
    st_name: "ac8    ",
    size: { l: "4800", t: "19.5", w: "140", ac: "7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marineart_woodtexture.png",
    fixigkit: "6",
    multi_language: {
      English: "MarineCap Wood-Texture Deep Embossed Baltic Brown",
      Dutch: "MarineCap getextureerde en veerkrachtige toplaag Baltic Brown",
      Danish: "MarineCap træ tekstur Baltic Brown",
      Swedish: "MarineCap Inkapslad Präglad Trä-Textur Baltic Brown",
      German: "Marine Cap Holzstruktur tief geprägt, Baltic Brown",
    },
  },
  {
    name: "MarineCap Baltic Grey Smooth",
    img: "https://i.ibb.co/55WKZpn/Marine-Cap-Side-2-Baltic-Grey.png    ",
    desc: "    ",
    cat: "marine_cap",
    price: "",
    st_name: "ac9    ",
    size: { l: "4800", t: "19.5", w: "140", ac: "7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marineart_woodtexture.png",
    fixigkit: "6",
    multi_language: {
      English: "MarineCap Smooth Baltic Grey",
      Dutch: "MarineCap glad geschaafd Baltic Grey",
      Danish: "MarineCap glat Baltic Grey",
      Swedish: "MarineCap Inkapslad Slät Baltic Grey",
      German: "Marine Cap glatt, Baltic Grey",
    },
  },
  {
    name: "MarineCap Baltic Brown Smooth",
    img: "https://i.ibb.co/hYJxdzg/Marine-Cap-Side-2-Baltic-Brown.png    ",
    desc: "",
    cat: "marine_cap",
    price: "",
    st_name: "ad1    ",
    size: { l: "4800", t: "19.5", w: "140", ac: "7" },
    j_dis: "2.50",
    j_length: "3600",
    no_pestals: "5",
    typeimage: "marineart_woodtexture.png",
    fixigkit: "6",
    multi_language: {
      English: "MarineCap Smooth Baltic Brown",
      Dutch: "MarineCap glad geschaafd Baltic Brown",
      Danish: "MarineCap glat Baltic Brown",
      Swedish: "MarineCap Inkapslad Slät Baltic Brown",
      German: "Marine Cap glatt, Baltic Brown",
    },
  },
  {
    name: "MarineJumbo Red Cherry Smooth",
    img: "https://i.ibb.co/xJpYTG1/Marine-Jumbo-Side-1-Red-Cherry.png    ",
    desc: "",
    cat: "marine_jumbo",
    price: "",
    st_name: "ad2",
    size: { l: "3600", t: "31", w: "225", ac: "4.4" },
    j_dis: "1.67",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marinejumbo_smoothsurface.png",
    fixigkit: "8",
    multi_language: {
      English: "MarineJumbo Smooth Red Cherry",
      Dutch: "MarineJumbo glad geschaafd Red Cherry",
      Danish: "MarineJumbo glat Red Cherry",
      Swedish: "MarineJumbo Slät Red Cherry",
      German: "Marine Jumbo glatt, Red Cherry",
    },
  },
  {
    name: "MarineJumbo Teak Smooth",
    img: "https://i.ibb.co/m42b4M0/Marine-Jumbo-Side-1-Teak.png    ",
    desc: "",
    cat: "marine_jumbo",
    price: "",
    st_name: "ad3    ",
    size: { l: "3600", t: "31", w: "225", ac: "4.4" },
    j_dis: "1.67",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marinejumbo_smoothsurface.png",
    fixigkit: "8",
    multi_language: {
      English: "MarineJumbo Smooth Teak",
      Dutch: "MarineJumbo glad geschaafd Teak",
      Danish: "MarineJumbo glat Teak",
      Swedish: "MarineJumbo Slät Teak",
      German: "Marine Jumbo glatt, Teak",
    },
  },
  {
    name: "MarineJumbo Beach Grey Smooth",
    img: "https://i.ibb.co/G576XR5/Marine-Jumbo-Side-1-Beach-Grey.png    ",
    desc: "",
    cat: "marine_jumbo",
    price: "",
    st_name: "ad4    ",
    size: { l: "3600", t: "31", w: "225", ac: "4.4" },
    j_dis: "1.67",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marinejumbo_smoothsurface.png",
    fixigkit: "8",
    multi_language: {
      English: "MarineJumbo Smooth Beach Grey",
      Dutch: "MarineJumbo glad geschaafd Beach Grey",
      Danish: "MarineJumbo glat Beach Grey",
      Swedish: "MarineJumbo Slät Beach Grey",
      German: "Marine Jumbo glatt, Beach Grey",
    },
  },
  {
    name: "MarineJumbo Red Cherry Narrow Ribbed",
    img: "https://i.ibb.co/fvjSwqJ/Marine-Jumbo-Side-2-Red-Cherry.png    ",
    desc: "Narrow lines    ",
    cat: "marine_jumbo",
    price: "",
    st_name: "ad5    ",
    size: { l: "3600", t: "31", w: "225", ac: "4.4" },
    j_dis: "1.67",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marinejumbo_narrow.png",
    fixigkit: "8",
    multi_language: {
      English: "MarineJumbo Narrow Ribbed Red Cherry",
      Dutch: "MarineJumbo fijn geribbeld Red Cherry",
      Danish: "MarineJumbo ribbet Red Cherry",
      Swedish: "MarineJumbo Smala Skåror Red Cherry",
      German: "Marine Jumbo schmal gerippt, Red Cherry",
    },
  },
  {
    name: "MarineJumbo Teak Narrow Ribbed",
    img: "https://i.ibb.co/yyHypt4/Marine-Jumbo-Side-2-Teak.png    ",
    desc: "Narrow lines    ",
    cat: "marine_jumbo",
    price: "",
    st_name: "ad6  ",
    size: { l: "3600", t: "31", w: "225", ac: "4.4" },
    j_dis: "1.67",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marinejumbo_narrow.png",
    fixigkit: "8",
    multi_language: {
      English: "MarineJumbo Narrow Ribbed Teak",
      Dutch: "MarineJumbo fijn geribbeld Teak",
      Danish: "MarineJumbo ribbet Teak",
      Swedish: "MarineJumbo Smala Skåror Teak",
      German: "Marine Jumbo schmal gerippt, Teak",
    },
  },
  {
    name: "MarineJumbo Beach Grey Narrow Ribbed",
    img: "https://i.ibb.co/ykgKccp/Marine-Jumbo-Side-2-Beach-Grey.png    ",
    desc: "Narrow lines    ",
    cat: "marine_jumbo",
    price: "",
    st_name: "ad7    ",
    size: { l: "3600", t: "31", w: "225", ac: "4.4" },
    j_dis: "1.67",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "marinejumbo_narrow.png",
    fixigkit: "8",
    multi_language: {
      English: "MarineJumbo Narrow Ribbed Beach Grey",
      Dutch: "MarineJumbo fijn geribbeld Beach Grey",
      Danish: "MarineJumbo ribbet Beach Grey",
      Swedish: "MarineJumbo Smala Skåror Beach Grey",
      German: "Marine Jumbo schmal gerippt, Beach Grey",
    },
  },
  {
    name: "Entra Beach Grey Narrow Ribbed",
    img: "https://i.ibb.co/18SKQJB/Entra-Side-1-Beach-Grey.png    ",
    desc: "Narrow lines    ",
    cat: "entra_side",
    price: "",
    st_name: "aa9    ",
    size: { l: "5000", t: "22", w: "150", ac: "6.4" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "entra_narrow.png",
    fixigkit: "3.5",
    multi_language: {
      English: "Entra Narrow Ribbed Beach Grey",
      Dutch: "Entra fijn geribbeld Beach Grey",
      Danish: "Entra ribbet Beach Grey",
      Swedish: "Entra Smal Räfflad Beach Grey",
      German: "Entra schmal gerippt, Beach Grey",
    },
  },
  {
    name: "Entra Charcoal Narrow Ribbed",
    img: "https://i.ibb.co/8rNChMc/Entra-Side-1-Charcoal.png    ",
    desc: "Narrow lines    ",
    cat: "entra_side",
    price: "",
    st_name: "ab1",
    size: { l: "5000", t: "22", w: "150", ac: "6.4" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "entra_narrow.png",
    fixigkit: "3.5",
    multi_language: {
      English: "Entra Narrow Ribbed Charcoal",
      Dutch: "Entra fijn geribbeld Charcoal",
      Danish: "Entra ribbet Charcoal",
      Swedish: "Entra Smal Räfflad Charcoal",
      German: "Entra schmal gerippt, Charcoal",
    },
  },
  {
    name: "Entra Chocolate Narrow Ribbed",
    img: "https://i.ibb.co/sK4jHhq/Entra-SIde-1-Chocolate.png    ",
    desc: "Narrow lines    ",
    cat: "entra_side",
    price: "",
    st_name: "ab2",
    size: { l: "5000", t: "22", w: "150", ac: "6.4" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "entra_narrow.png",
    fixigkit: "3.5",
    multi_language: {
      English: "Entra Narrow Ribbed Chocolate",
      Dutch: "Entra fijn geribbeld Chocolate",
      Danish: "Entra ribbet Chocolate",
      Swedish: "Entra Smal Räfflad Chocolate",
      German: "Entra schmal gerippt, Chocolate",
    },
  },
  {
    name: "Entra Teak Narrow Ribbed",
    img: "https://i.ibb.co/8Pymntj/Entra-Side-1-Teak.png    ",
    desc: "Narrow lines    ",
    cat: "entra_side",
    price: "",
    st_name: "ab3    ",
    size: { l: "5000", t: "22", w: "150", ac: "6.4" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "entra_narrow.png",
    fixigkit: "3.5",
    multi_language: {
      English: "Entra Narrow Ribbed Teak",
      Dutch: "Entra fijn geribbeld Teak",
      Danish: "Entra ribbet Teak",
      Swedish: "Entra Smal Räfflad Teak",
      German: "Entra schmal gerippt, Teak",
    },
  },
  {
    name: "Entra Beach Grey Wood-Texture",
    img: "https://i.ibb.co/MprRB7N/Entra-Side-2-Beach-Grey.png    ",
    desc: "wood-texture    ",
    cat: "entra_side",
    price: "",
    st_name: "ab4    ",
    size: { l: "5000", t: "22", w: "150", ac: "6.4" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "entra_wide.png",
    fixigkit: "3.5",
    multi_language: {
      English: "Entra Narrow Wood-Texture Beach Grey",
      Dutch: "Entra details van echt hout Beach Grey",
      Danish: "Entra træ tekstur Beach Grey",
      Swedish: "Entra Trä-Textur Beach Grey",
      German: "Entra mit schmalen Holztextur, Beach Grey",
    },
  },
  {
    name: "Entra Charcoal Wood-Texture",
    img: "https://i.ibb.co/GVpLc05/Entra-Side-2-Charcoal.png    ",
    desc: "wood-texture    ",
    cat: "entra_side",
    price: "",
    st_name: "ab5    ",
    size: { l: "5000", t: "22", w: "150", ac: "6.4" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "entra_wide.png",
    fixigkit: "3.5",
    multi_language: {
      English: "Entra Narrow Wood-Texture Charcoal",
      Dutch: "Entra details van echt hout Charcoal",
      Danish: "Entra træ tekstur Charcoal",
      Swedish: "Entra Trä-Textur Charcoal",
      German: "Entra mit schmalen Holztextur, Charcoal",
    },
  },
  {
    name: "Entra Chocolate Wood-Texture",
    img: "https://i.ibb.co/N2D63Qv/Entra-Side-2-Chocolate.png    ",
    desc: "wood-texture    ",
    cat: "entra_side",
    price: "",
    st_name: "ab6    ",
    size: { l: "5000", t: "22", w: "150", ac: "6.4" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "entra_wide.png",
    fixigkit: "3.5",
    multi_language: {
      English: "Entra Narrow Wood-Texture Chocolate",
      Dutch: "Entra details van echt hout Chocolate",
      Danish: "Entra træ tekstur Chocolate",
      Swedish: "Entra Trä-Textur Chocolate",
      German: "Entra mit schmalen Holztextur, Chocolate",
    },
  },
  {
    name: "Entra Teak Wood-Texture",
    img: "https://i.ibb.co/F5bXXsR/Entra-Side-2-Teak.png    ",
    desc: "wood-texture    ",
    cat: "entra_side",
    price: "",
    st_name: "ab7    ",
    size: { l: "5000", t: "22", w: "150", ac: "6.4" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "entra_wide.png",
    fixigkit: "3.5",
    multi_language: {
      English: "Entra Narrow Wood-Texture Teak",
      Dutch: "Entra details van echt hout Teak",
      Danish: "Entra træ tekstur Teak",
      Swedish: "Entra Trä-Textur Teak",
      German: "Entra mit schmalen Holztextur, Teak",
    },
  },
  {
    name: "Classic Beach Grey Wide Groove",
    img: "https://i.ibb.co/vJNnPZN/Classic-Side-1-Beach-Grey.png",
    desc: "Wide lines    ",
    cat: "classic",
    price: "",
    st_name: "aa1",
    size: { l: "3800", t: "24", w: "135", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "classic_narrow.png",
    fixigkit: "7",
    multi_language: {
      English: "Classic Wide Groove Beach Grey 1",
      Dutch: "Classic brede groef Beach Grey",
      Danish: "Classic bred rillet Beach Grey",
      Swedish: "Classic Breda Skåror Beach Grey",
      German: "Klassische breite Rille, Beach Grey",
    },
  },
  {
    name: "Classic Charcoal Wide Groove",
    img: "https://i.ibb.co/gDQFgTc/Classic-side-1-Charcoal.png",
    desc: "Wide lines    ",
    cat: "classic",
    price: "",
    st_name: "aa2",
    size: { l: "4800", t: "24", w: "135", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "classic_narrow.png",
    fixigkit: "7",
    multi_language: {
      English: "Classic Wide Groove Charcoal",
      Dutch: "Classic brede groef Charcoal",
      Danish: "Classic bred rillet Charcoal",
      Swedish: "Classic Breda Skåror Charcoal",
      German: "Klassische breite Rille,  Charcoal",
    },
  },
  {
    name: "Classic Chocolate Wide Groove",
    img: "https://i.ibb.co/Bswky20/Classic-Side-1-Chocolate.png",
    desc: "Wide lines      ",
    cat: "classic",
    price: "",
    st_name: "aa3    ",
    size: { l: "4800", t: "24", w: "135", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "classic_narrow.png",
    fixigkit: "7",
    multi_language: {
      English: "Classic Wide Groove Chocolate",
      Dutch: "Classic brede groef Chocolate",
      Danish: "Classic bred rillet Chocolate",
      Swedish: "Classic Breda Skåror Chocolate",
      German: "Klassische breite Rille, Chocolate",
    },
  },
  {
    name: "Classic Teak Wide Groove",
    img: "https://i.ibb.co/6WN8psS/Classic-Side-1-Teak.png    ",
    desc: "Wide lines      ",
    cat: "classic",
    price: "",
    st_name: "aa4    ",
    size: { l: "3800", t: "24", w: "135", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "classic_narrow.png",
    fixigkit: "7",
    multi_language: {
      English: "Classic Wide Groove Teak",
      Dutch: "Classic brede groef Teak",
      Danish: "Classic bred rillet Teak",
      Swedish: "Classic Breda Skåror Teak",
      German: "Klassische breite Rille, Teak",
    },
  },
  {
    name: "Classic Beach Grey Narrow Groove",
    img: "https://i.ibb.co/CQc2hkb/Classic-Side-2-Beach-Grey.png    ",
    desc: "Narrow lines    ",
    cat: "classic",
    price: "",
    st_name: "aa5    ",
    size: { l: "3800", t: "24", w: "135", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "classic_wide.png",
    fixigkit: "7",
    multi_language: {
      English: "Classic Narrow Groove Beach Grey",
      Dutch: "Classic smalle groef Beach Grey",
      Danish: "Classic smal rillet Beach Grey",
      Swedish: "Classic Smala Skåror Beach Grey",
      German: "Klassische schmale Rille, Beach Grey",
    },
  },
  {
    name: "Classic Charcoal Narrow Groove",
    img: "https://i.ibb.co/bzP6FY0/Classic-Side-2-Charcoal.png    ",
    desc: "Narrow lines  ",
    cat: "classic",
    price: "",
    st_name: "aa6    ",
    size: { l: "4800", t: "24", w: "135", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "classic_wide.png",
    fixigkit: "7",
    multi_language: {
      English: "Classic Narrow Groove Charcoal",
      Dutch: "Classic smalle groef Charcoal",
      Danish: "Classic smal rillet Charcoal",
      Swedish: "Classic Smala Skåror Charcoal",
      German: "Klassische schmale Rille, Charcoal",
    },
  },
  {
    name: "Classic Chocolate Narrow Groove",
    img: "https://i.ibb.co/6bVFCwj/Classic-Side-2-Chocolate.png    ",
    desc: "Narrow lines  ",
    cat: "classic",
    price: "",
    st_name: "aa7    ",
    size: { l: "4800", t: "24", w: "135", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "classic_wide.png",
    fixigkit: "7",
    multi_language: {
      English: "Classic Narrow Groove Chocolate",
      Dutch: "Classic smalle groef Chocolate",
      Danish: "Classic smal rillet Chocolate",
      Swedish: "Classic Smala Skåror Chocolate",
      German: "Klassische schmale Rille, Chocolate",
    },
  },
  {
    name: "Classic Teak Narrow Groove",
    img: "https://i.ibb.co/whZWQ4x/Classic-Side-2-Teak.png    ",
    desc: "Narrow lines  ",
    cat: "classic",
    price: "",
    st_name: "aa8    ",
    size: { l: "3800", t: "24", w: "135", ac: "7.1" },
    j_dis: "2.00",
    j_length: "3600",
    no_pestals: "4",
    typeimage: "classic_wide.png",
    fixigkit: "7",
    multi_language: {
      English: "Classic Narrow Groove Teak",
      Dutch: "Classic smalle groef Teak",
      Danish: "Classic smal rillet Teak",
      Swedish: "Classic Smala Skåror Teak",
      German: "Klassische schmale Rille, Teak",
    },
  },
  {
    name: "EverDeck Beach Grey Narrow Ribbed",
    img: "https://i.ibb.co/wyKSqD0/Everdeck-Side-1-Beach-Grey.png    ",
    desc: "Narrow lines    ",
    cat: "ever_deck",
    price: "",
    st_name: "ab8    ",
    size: { l: "2900", t: "23", w: "146", ac: "6.7" },
    j_dis: "3.30",
    j_length: "2900",
    no_pestals: "6",
    typeimage: "everdeck_narrow.png",
    fixigkit: "3.5",
    multi_language: {
      English: "EverDeck Narrow Ribbed Beach Grey",
      Dutch: "EverDeck fijn geribbeld Beach Grey",
      Danish: "EverDeck ribbet Beach Grey",
      Swedish: "Everdeck Smal Räfflad Beach Grey",
      German: "EverDeck schmal gerippt, Beach Grey",
    },
  },
  {
    name: "EverDeck Charcoal Narrow Ribbed",
    img: "https://i.ibb.co/ZfnLgDG/Everdeck-Side-1-Charcoal.png    ",
    desc: "Narrow lines    ",
    cat: "ever_deck",
    price: "",
    st_name: "ab9    ",
    size: { l: "2900", t: "23", w: "146", ac: "6.7" },
    j_dis: "3.30",
    j_length: "2900",
    no_pestals: "6",
    typeimage: "everdeck_narrow.png",
    fixigkit: "5",
    multi_language: {
      English: "EverDeck Narrow Ribbed Charcoal",
      Dutch: "EverDeck fijn geribbeld Charcoal",
      Danish: "EverDeck ribbet Charcoal",
      Swedish: "Everdeck Smal Räfflad Charcoal",
      German: "EverDeck schmal gerippt, Charcoal",
    },
  },
  {
    name: "EverDeck Beach Grey Smooth",
    img: "https://i.ibb.co/qdcyZSr/Everdeck-Side-2-Beach-Grey.png    ",
    desc: "",
    cat: "ever_deck",
    price: "",
    st_name: "ac1",
    size: { l: "2900", t: "23", w: "146", ac: "6.7" },
    j_dis: "3.30",
    j_length: "2900",
    no_pestals: "6",
    typeimage: "everdeck.png",
    fixigkit: "5",
    multi_language: {
      English: "EverDeck Smooth Beach Grey",
      Dutch: "EverDeck glad geschaafd Beach Grey",
      Danish: "EverDeck glat Beach Grey",
      Swedish: "Everdeck Slät Beach Grey",
      German: "EverDeck glatt, Beach Grey",
    },
  },
  {
    name: "EverDeck Charcoal Smooth",
    img: "https://i.ibb.co/h9XpTn4/Everdeck-Side-2-Charcoal.png    ",
    desc: "",
    cat: "ever_deck",
    price: "",
    st_name: "ac2 ",
    size: { l: "2900", t: "23", w: "146", ac: "6.7" },
    j_dis: "3.30",
    j_length: "2900",
    no_pestals: "6",
    typeimage: "everdeck.png",
    fixigkit: "5",
    multi_language: {
      English: "EverDeck Smooth Charcoal",
      Dutch: "EverDeck glad geschaafd Charcoal",
      Danish: "EverDeck glat Charcoal",
      Swedish: "Everdeck Slät Charcoal",
      German: "EverDeck glatt, Charcoal",
    },
  }
];
